version: '3'
services:
  top.api:
    image: top-api:latest
    container_name: top-api
    restart: always
    ports: 
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017